spring:
  application:
    name: countriesList
  datasource:
    url: jdbc:postgresql://localhost:5432/countrydb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8083